/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cognito_identity_pool_id": "ca-central-1:71648ac7-f618-4858-a8a4-b73e563fe185",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_dDdSO9ATs",
    "aws_user_pools_web_client_id": "d2la8i1dsnl2gug62ca5douhk",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://63aaohifrrg4dkfu2awzmejlca.appsync-api.ca-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "ca-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-pkl2t7tu7fci3lxcayfnh7bs7y",
    "aws_content_delivery_bucket": "yyelp-20240528202929-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "ca-central-1",
    "aws_content_delivery_url": "https://d3pig1xpqw2ql7.cloudfront.net"
};


export default awsmobile;
